
import { ShieldAlert } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto py-8 px-4 md:px-6">
      <header className="text-center mb-12">
        <ShieldAlert className="h-16 w-16 text-primary mx-auto mb-4" />
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl font-headline text-primary">
          Hardware Simulation Disclaimer
        </h1>
        <p className="mt-4 text-xl text-foreground/80 max-w-3xl mx-auto text-balance">
          Last Updated: May 28, 2026
        </p>
      </header>

      <div className="max-w-3xl mx-auto space-y-8 bg-card p-6 sm:p-8 rounded-xl shadow-lg text-foreground/80">
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">Estimations Only</h2>
          <p className="leading-relaxed text-balance">
            TokenCalc is a specialized technical resource for estimating Large Language Model (LLM) VRAM consumption. The results generated by this tool are theoretical simulations based on publicly available architecture specifications and mathematical heuristics. 
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">1. No Performance Guarantee</h2>
          <p className="leading-relaxed text-balance">
            Real-world VRAM usage can vary significantly based on your specific inference engine (e.g., vLLM, llama.cpp, Ollama), operating system overhead, and driver versions. TokenCalc results should be used as a general guide and not as a definitive guarantee of hardware compatibility.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">2. Third-Party Model Weights</h2>
          <p className="leading-relaxed text-balance">
            TokenCalc is not affiliated with any AI model providers (Meta, Mistral, Google, etc.). We do not host model weights or proprietary model definitions. Our calculations are based on standard transformer block logic.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">3. No Data Liability</h2>
          <p className="leading-relaxed text-balance">
            TokenCalc and its developers are not liable for any Out-Of-Memory (OOM) errors, system crashes, or hardware damage resulting from deployment decisions based on our estimates. Always perform independent benchmarking before purchasing or leasing significant AI compute resources.
          </p>
        </section>

        <p className="text-center font-semibold text-foreground/90 pt-4">
          By using TokenCalc, you acknowledge that you have read, understood, and agreed to this hardware simulation disclaimer.
        </p>
      </div>
    </div>
  );
}
