
import { ShieldCheck, BookOpen, Scale, Globe } from 'lucide-react';

export default function RightsPage() {
  return (
    <div className="container mx-auto py-8 px-4 md:px-6">
      <header className="text-center mb-12">
        <ShieldCheck className="h-16 w-16 text-primary mx-auto mb-4" />
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl font-headline text-primary">
          Intellectual Property & Content Rights
        </h1>
        <p className="mt-4 text-xl text-foreground/80 max-w-3xl mx-auto text-balance">
          Governing the use of TokenCalc architectural resources
        </p>
      </header>

      <div className="max-w-3xl mx-auto space-y-8 bg-card p-6 sm:p-8 rounded-xl shadow-lg text-foreground/80">
        <section>
          <div className="flex items-center gap-2 mb-3 text-primary">
            <BookOpen className="h-6 w-6" />
            <h2 className="text-2xl font-semibold text-foreground">1. Ownership of Estimates</h2>
          </div>
          <p className="leading-relaxed text-balance">
            Any hardware configuration, VRAM estimate, or architecture roadmap developed using TokenCalc is the property of the user. We claim no intellectual property rights over the infrastructure plans generated by our tool.
          </p>
        </section>

        <section>
          <div className="flex items-center gap-2 mb-3 text-primary">
            <Scale className="h-6 w-6" />
            <h2 className="text-2xl font-semibold text-foreground">2. Tool IP</h2>
          </div>
          <p className="leading-relaxed text-balance">
            The visual logic, client-side JS math engine, and the brand identity of "TokenCalc" are the exclusive intellectual property of our developers. You are granted a limited, non-exclusive license to use these resources for professional AI infrastructure planning.
          </p>
        </section>

        <section>
          <div className="flex items-center gap-2 mb-3 text-primary">
            <Globe className="h-6 w-6" />
            <h2 className="text-2xl font-semibold text-foreground">3. Knowledge Base Usage</h2>
          </div>
          <p className="leading-relaxed text-balance">
            Our technical articles and VRAM optimization guides are provided for the benefit of the AI engineering community. You may reference our guides in internal wikis or whitepapers with proper attribution to TokenCalc. Mass scraping or repackaging of our Knowledge Base for commercial resale is strictly prohibited.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">4. Hardware Vendor Trademarks</h2>
          <p className="leading-relaxed text-balance">
            NVIDIA, CUDA, RTX, H100, and other hardware-related names are trademarks of their respective owners. TokenCalc mentions these terms purely for technical identification and recommendation purposes within our simulation logic.
          </p>
        </section>

        <p className="text-center font-semibold text-foreground/90 pt-4 border-t border-foreground/20">
          TokenCalc is committed to supporting the growth of a transparent and decentralized AI infrastructure ecosystem.
        </p>
      </div>
    </div>
  );
}
